<a href="https://colab.research.google.com/github/simrathanspal/deep_models_from_scratch/blob/main/DeepLearning_Book_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Intro to NumPy

In [1]:
import numpy as np
import math


Notations


Capital letter will represent matrix or a tensor and small letter will represent scalar or a vector

In [7]:
# Scalar is a single number eg: 5
scalar_list = [5]

In [8]:
# Vector is a list of number

vector = [1,2,3]

# Row vector
[[1,2,3]]

# Column vector
[[1],[2],[3]]

In [9]:
#Matrix is 2D array of numbers, basically a container of vectors
matrix = [[1,2,3],
          [4,5,6]]

In [11]:
# Tensor is a higher order matrix with more than 2 dimensions

tensor = [[[1,2],
            [3,4]],
          [[5,6],
            [7,8]]
          ]

In [17]:
# Shape - number of dimensions

print(f"Shape of scalar: {np.array(scalar_list).shape}")
print(f"Shape of vector: {np.array(vector).shape}")
print(f"Shape of matrix: {np.array(matrix).shape}")
print(f"Shape of tensor: {np.array(tensor).shape}")

Shape of scalar: (1,)
Shape of vector: (3,)
Shape of matrix: (2, 3)
Shape of tensor: (2, 2, 2)


In [16]:
# Rank of matrix = number of independent rows or columns
# (amount of unique information)
# Since Row2 is 2*Row1 and Row3 is 3*Row1
# The Rank of the matrix is just 1

np.linalg.matrix_rank(np.array([[1, 2, 3],
                                  [2, 4, 6],
                                  [3, 6, 9]]))

np.int64(1)

In [20]:
np.linalg.matrix_rank(np.array([[1,2,3],
                                [4,5,6]]))

np.int64(2)

In [14]:
# Here we are computing the shape and then computing the rank of it
# For example shape of matrix = [[1,2,3], [4,5,6]] => (2,3)
# Numpy converts it to [2,3] and this is 1 independent row hence rank is 1

print(f"Shape of scalar: {np.linalg.matrix_rank(np.array(scalar_list).shape)}")
print(f"Shape of vector: {np.linalg.matrix_rank(np.array(vector).shape)}")
print(f"Shape of matrix: {np.linalg.matrix_rank(np.array(matrix).shape)}")
print(f"Shape of tensor: {np.linalg.matrix_rank(np.array(tensor).shape)}")

Shape of scalar: 1
Shape of vector: 1
Shape of matrix: 1
Shape of tensor: 1


In [21]:
# Indexing

A = np.arange(12).reshape(3,4)

A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
# Index a specific position row=i and col=j
# A[i,j]

A[2,3]

np.int64(11)

In [25]:
# All values of a specific column
A[:,3]

array([ 3,  7, 11])

In [27]:
# All values of a specific row
# A[2,:] or simply A[2]

A[2]

array([ 8,  9, 10, 11])

In [28]:
# Print the whole array
# A[:,:] or simply A
A[:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
# Matrix Addition - Element wise scalar addition
# A + a
# This would add scalar value to every element of A
# Numpy internally broadcast to create a new array of same size as A and then add

A = np.array([[1,2],[3,4],[5,6]])

A + 10



array([[11, 12],
       [13, 14],
       [15, 16]])

In [33]:
# Matrix addition needs to be same shapes because it is element wise addition
# i.e (A_i, A_j) will get summed with (B_i, B_j)

# Lets check out this example
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[2,4,6],[1,2,3]])

print(f"Shape of A: {A.shape}")
print(f"Shape of B: {B.shape}")

A+B

Shape of A: (3, 2)
Shape of B: (2, 3)


ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [34]:
# Matrix multiplication - Element wise multiplication
# Same way multiplication also needs same size
# Numpy function is called np.multiply
# Shorthand notation A*B

A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[2,4,6],[1,2,3]])

C = A*B
C

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [30]:
# Numpy matmul
# sum (col of M1 * row of M2)
# Hence the inner dimensions must match
# eg: (x,m) (m,y)
# Short hand notation A@B
# Example 1,3,4 * 2,4,6 => (1*2) + (3*4) + (4*6)

C = np.matmul(A, B)
C

array([[ 4,  8, 12],
       [10, 20, 30],
       [16, 32, 48]])

In [37]:
np.dot(np.array([[1, 2], [3, 4]]), 10)

array([[10, 20],
       [30, 40]])

In [42]:
# Transpose - flips a matrix along its diagonal
# Rows become the col and col become rows

print(A)
print("\nTranspose")
np.transpose(A)

[[1 2]
 [3 4]
 [5 6]]

Transpose


array([[1, 3, 5],
       [2, 4, 6]])

In [47]:
# Identity and Inverse Matrix
# If you multiply (A-1)A = I (identity matrix)

A = np.random.rand(2,2)

I = np.matmul(np.linalg.inv(A), A)
I_ = np.identity(2)

I == I_

array([[False, False],
       [False, False]])

In [46]:
# Note we did exactly the same as expected still the identity matrix is not matching.
# This is happening because of floating point numbers

In [48]:
I

array([[1.00000000e+00, 8.45832772e-17],
       [5.31181241e-18, 1.00000000e+00]])

In [49]:
# Hence let us define tolerance range and the compare

np.allclose(I, I_)

True

In [52]:
# Not all matrix inverse exists hence we can use
# Moore-Penrose psuedo inverse of the matrix => closest to inverse
# Matrix inversion is not defined for matrix that is not square

np.matmul(np.linalg.pinv(A), A)

array([[1.00000000e+00, 3.54144662e-16],
       [5.07400348e-16, 1.00000000e+00]])

In [53]:
# Norm - size of a vector
# Norm of vector x is the distance from origin to point x
# Imagine a vector starting from origin and touching point x, that is also the
# length of the vector

# L_p norm = (Sigma(value_i^p))^(1/p)

#L2 norm is the euclidean norm which is the euclidean distance of the point from origin
# Hence denoted as ||x|| (or ||x||2)

np.linalg.norm(np.array([3,4]))


np.float64(5.0)

In [ ]:
# Special kind of matrices

# 1) Diagonal matrix, special case is Identity matrix with all diagonal values as 1
# np.diag(Matrix) => returns the diagonal
# 2) Identity matrix
# 3) Symmetric matrix matrix transpose = matrix, MT = M
# 4) Unit vector is a vector with unit norm
# 5) Orthogonal vectors x(T).y = 0
# 6) If the vectors are Orthogonal and have unit norm => Orthonormal
# 7) Orthogonal matrix => Rows are mutually orthonormal and cols are mutually
# orthonormal.
# A-1.A = I
# but if AT.A = I
# => A-1 = AT


In [ ]:
# Eigen decomposition
# Breaking down to prime component tells us about the matrix

# Matrix eigen decomposition => decomposed into eigen vector and values

# If matrix has n eigen vectors

eig_val, eig_vector = np.linalg.eig(A)

# When we multiply matrix with eigen vector it scales and becomes elipse
# Sclaing fact is lambda
# A.eigen_vector = lambda.eigen_vector
# pg:41




In [ ]:
# Singular value decomposition
# Another way to decompose to vector and value
# Every matrix has a SVD decomposition but not necessarily eigen decomposition

#

np.linalg.svd(A)

In [ ]:
# Determinant of a matrix is the product of all eigen values of the matrix
# If determinant is 0 that means the space is contracted completely, atleast in
# one dimension.

np.linalg.det(I)